#include "codegen_logic.h"

namespace gdsl {

static const char *c_scalar_type(ValueType t) {
	switch (t) {
		case ValueType::Int: return "int64_t";
		case ValueType::Float: return "double";
		case ValueType::Bool: return "bool";
		case ValueType::String: return "char *";
		default: return "void *";
	}
}

std::string emit_c(const TypedProgram &prog) {
	std::string out;
	out += "/* Generated by gdsl. Do not edit. */\n";
	out += "#include <stdint.h>\n";
	out += "\n";
	for (const TypedType &t : prog.types) {
		out += "typedef struct " + t.name + " {\n";
		for (const TypedField &f : t.fields) {
			std::string ct;
			if (f.type == ValueType::Named) {
				ct = f.type_name + " *";
			} else {
				ct = c_scalar_type(f.type);
			}
			out += "\t" + ct + " " + f.name + "; /* " + f.default_value + " */\n";
		}
		out += "} " + t.name + ";\n";
		out += "\n";
	}
	for (const TypedRule &r : prog.rules) {
		out += "/* rule " + r.name + " by " + r.by + ": when `" + r.when + "` then `" + r.then + "` */\n";
	}
	return out;
}

} // namespace gdsl
