#include "codegen_logic.h"
#include "abihash.h"

namespace gdsl {

static const char *c_scalar_type(ValueType t) {
	switch (t) {
		case ValueType::Int: return "int64_t";
		case ValueType::Float: return "double";
		case ValueType::Bool: return "bool";
		case ValueType::String: return "char *";
		default: return "void *";
	}
}

// 字段 Variant 类型（GDExtensionVariantType 枚举名）。仅标量；Named/String 单独处理。
static const char *variant_type(ValueType t) {
	switch (t) {
		case ValueType::Int: return "GDEXTENSION_VARIANT_TYPE_INT";
		case ValueType::Float: return "GDEXTENSION_VARIANT_TYPE_FLOAT";
		case ValueType::Bool: return "GDEXTENSION_VARIANT_TYPE_BOOL";
		default: return nullptr;
	}
}

// 字段 C 类型：Named 映射为指向该类型 struct 的指针。
static std::string c_field_type(const TypedField &f) {
	if (f.type == ValueType::Named) {
		return f.type_name + " *";
	}
	return c_scalar_type(f.type);
}

// 字段默认值的 C 字面量。Named → NULL；String → 加引号；其余原样。
static std::string default_literal(const TypedField &f) {
	if (f.type == ValueType::Named) {
		return "NULL";
	}
	if (f.type == ValueType::String) {
		return "\"" + f.default_value + "\"";
	}
	return f.default_value;
}

// 类型名首字母小写，用作函数前缀（Player -> player）。
static std::string fn_prefix(const std::string &name) {
	std::string p = name;
	if (!p.empty() && p[0] >= 'A' && p[0] <= 'Z') {
		p[0] = p[0] - 'A' + 'a';
	}
	return p;
}

// CamelCase → snake_case（OnHit -> on_hit，TakeDamage -> take_damage）。
static std::string to_snake_case(const std::string &name) {
	std::string out;
	for (size_t i = 0; i < name.size(); i++) {
		char c = name[i];
		if (c >= 'A' && c <= 'Z') {
			if (i > 0 && !out.empty()) {
				char prev = name[i - 1];
				if ((prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9')) {
					out += '_';
				}
			}
			out += (char)(c - 'A' + 'a');
		} else {
			out += c;
		}
	}
	return out;
}

// 收集规则里所有 emit 信号名（去重，保持首次出现顺序，确定性）。
static std::vector<std::string> collect_signal_names(const TypedProgram &prog) {
	std::vector<std::string> names;
	for (const TypedRule &r : prog.rules) {
		for (const Effect &fx : r.effects) {
			if (fx.kind != EffectKind::Emit) {
				continue;
			}
			bool seen = false;
			for (const std::string &n : names) {
				if (n == fx.signal_name) {
					seen = true;
					break;
				}
			}
			if (!seen) {
				names.push_back(fx.signal_name);
			}
		}
	}
	return names;
}

std::string emit_c(const TypedProgram &prog) {
	std::string out;
	const std::vector<std::string> signal_names = collect_signal_names(prog);
	const std::string emit_hash = std::to_string(emit_signal_compat_hash());

	// ---- 文件头 + GDE_EXPORT ----
	out += "/* Generated by gdsl. Do not edit. */\n";
	out += "#include <gdextension_interface.h>\n";
	out += "#include <stdbool.h>\n";
	out += "#include <stddef.h>\n";
	out += "#include <stdint.h>\n";
	out += "\n";
	out += "#if !defined(GDE_EXPORT)\n";
	out += "#if defined(_WIN32)\n";
	out += "#define GDE_EXPORT __declspec(dllexport)\n";
	out += "#elif defined(__GNUC__)\n";
	out += "#define GDE_EXPORT __attribute__((visibility(\"default\")))\n";
	out += "#else\n";
	out += "#define GDE_EXPORT\n";
	out += "#endif\n";
	out += "#endif\n";
	out += "\n";

	// ---- API 缓存 + load_api ----
	out += "/* ---- GDExtension API cache ---- */\n";
	out += "static GDExtensionClassLibraryPtr gdsl_library = NULL;\n";
	out += "\n";
	out += "static GDExtensionInterfaceStringNameNewWithLatin1Chars gdsl_string_name_new;\n";
	out += "static GDExtensionInterfaceClassdbConstructObject gdsl_classdb_construct_object;\n";
	out += "static GDExtensionInterfaceObjectSetInstance gdsl_object_set_instance;\n";
	out += "static GDExtensionInterfaceMemAlloc gdsl_mem_alloc;\n";
	out += "static GDExtensionInterfaceMemFree gdsl_mem_free;\n";
	out += "static GDExtensionInterfaceClassdbRegisterExtensionClass6 gdsl_classdb_register_extension_class6;\n";
	out += "static GDExtensionInterfaceClassdbRegisterExtensionClassMethod gdsl_classdb_register_extension_class_method;\n";
	out += "static GDExtensionInterfaceClassdbGetMethodBind gdsl_classdb_get_method_bind;\n";
	out += "static GDExtensionInterfaceObjectMethodBindCall gdsl_object_method_bind_call;\n";
	out += "static GDExtensionInterfaceGetVariantFromTypeConstructor gdsl_get_variant_from_type_constructor;\n";
	out += "static GDExtensionInterfaceVariantDestroy gdsl_variant_destroy;\n";
	out += "static GDExtensionInterfaceVariantNewNil gdsl_variant_new_nil;\n";
	out += "static GDExtensionInterfaceVariantGetType gdsl_variant_get_type;\n";
	out += "static GDExtensionInterfaceObjectSetInstanceBinding gdsl_object_set_instance_binding;\n";
	out += "static GDExtensionInterfaceObjectGetInstanceBinding gdsl_object_get_instance_binding;\n";
	out += "static GDExtensionInterfaceGetVariantToTypeConstructor gdsl_get_variant_to_type_constructor;\n";
	out += "static GDExtensionInterfaceClassdbUnregisterExtensionClass gdsl_classdb_unregister_extension_class;\n";
	out += "static GDExtensionInterfaceClassdbRegisterExtensionClassProperty gdsl_classdb_register_extension_class_property;\n";
	out += "\n";
	out += "static void gdsl_load_api(GDExtensionInterfaceGetProcAddress p_get_proc_address) {\n";
	out += "\tgdsl_string_name_new = (GDExtensionInterfaceStringNameNewWithLatin1Chars)p_get_proc_address(\"string_name_new_with_latin1_chars\");\n";
	out += "\tgdsl_classdb_construct_object = (GDExtensionInterfaceClassdbConstructObject)p_get_proc_address(\"classdb_construct_object\");\n";
	out += "\tgdsl_object_set_instance = (GDExtensionInterfaceObjectSetInstance)p_get_proc_address(\"object_set_instance\");\n";
	out += "\tgdsl_mem_alloc = (GDExtensionInterfaceMemAlloc)p_get_proc_address(\"mem_alloc\");\n";
	out += "\tgdsl_mem_free = (GDExtensionInterfaceMemFree)p_get_proc_address(\"mem_free\");\n";
	out += "\tgdsl_classdb_register_extension_class6 = (GDExtensionInterfaceClassdbRegisterExtensionClass6)p_get_proc_address(\"classdb_register_extension_class6\");\n";
	out += "\tgdsl_classdb_register_extension_class_method = (GDExtensionInterfaceClassdbRegisterExtensionClassMethod)p_get_proc_address(\"classdb_register_extension_class_method\");\n";
	out += "\tgdsl_classdb_get_method_bind = (GDExtensionInterfaceClassdbGetMethodBind)p_get_proc_address(\"classdb_get_method_bind\");\n";
	out += "\tgdsl_object_method_bind_call = (GDExtensionInterfaceObjectMethodBindCall)p_get_proc_address(\"object_method_bind_call\");\n";
	out += "\tgdsl_get_variant_from_type_constructor = (GDExtensionInterfaceGetVariantFromTypeConstructor)p_get_proc_address(\"get_variant_from_type_constructor\");\n";
	out += "	gdsl_variant_destroy = (GDExtensionInterfaceVariantDestroy)p_get_proc_address(\"variant_destroy\");\n";
	out += "	gdsl_variant_new_nil = (GDExtensionInterfaceVariantNewNil)p_get_proc_address(\"variant_new_nil\");\n";
	out += "	gdsl_variant_get_type = (GDExtensionInterfaceVariantGetType)p_get_proc_address(\"variant_get_type\");\n";
	out += "	gdsl_object_set_instance_binding = (GDExtensionInterfaceObjectSetInstanceBinding)p_get_proc_address(\"object_set_instance_binding\");\n";
	out += "	gdsl_object_get_instance_binding = (GDExtensionInterfaceObjectGetInstanceBinding)p_get_proc_address(\"object_get_instance_binding\");\n";
	out += "	gdsl_get_variant_to_type_constructor = (GDExtensionInterfaceGetVariantToTypeConstructor)p_get_proc_address(\"get_variant_to_type_constructor\");\n";
	out += "	gdsl_classdb_unregister_extension_class = (GDExtensionInterfaceClassdbUnregisterExtensionClass)p_get_proc_address(\"classdb_unregister_extension_class\");\n";
	out += "	gdsl_classdb_register_extension_class_property = (GDExtensionInterfaceClassdbRegisterExtensionClassProperty)p_get_proc_address(\"classdb_register_extension_class_property\");\n";
	out += "}\n";
	out += "\n";

	// ---- StringName / Variant 占位 ----
	out += "/* StringName opaque holder (64-bit build: 8 bytes). */\n";
	out += "typedef struct {\n";
	out += "	uint8_t data[8];\n";
	out += "} gdsl_StringName;\n";
	out += "\n";
	out += "/* Variant opaque holder (single-precision 64-bit build: 24 bytes, 8-aligned). */\n";
	out += "typedef union {\n";
	out += "	uint64_t align_;\n";
	out += "	uint8_t data[24];\n";
	out += "} gdsl_Variant;\n";
	out += "\n";
	// FR-004/009 真机崩溃根因：引擎 PropertyInfo(const GDExtensionPropertyInfo&)
	// 无条件解引用 hint_string（core/object/property_info.h:168），传 NULL 必崩。
	// String 是单指针成员（8 字节），零初始化即空字符串，COW 对 nullptr 安全。
	out += "/* 空 String（8 字节零初始化 = 空字符串）。PropertyInfo 构造会解引用 hint_string，\n";
	out += " * 不能传 NULL，故提供这个零初始化占位。 */\n";
	out += "static uint8_t gdsl_empty_string[8] = { 0 };\n";
	out += "\n";
	out += "/* Object::emit_signal MethodBind，SCENE 初始化时缓存一次。 */\n";
	out += "static GDExtensionMethodBindPtr gdsl_emit_signal_mb = NULL;\n";
	out += "\n";
	out += "/* Instance binding callbacks：把每个 DSL 对象的 C struct 挂到对象上，供跨参与者 target 取回。\n";
	out += " * free_callback 置 NULL —— 内存由扩展的 free_instance_func 统一释放，避免双重释放。 */\n";
	out += "static void *gdsl_binding_create(void *p_token, GDExtensionObjectPtr p_instance) {\n";
	out += "	(void)p_token;\n";
	out += "	(void)p_instance;\n";
	out += "	return NULL;\n";
	out += "}\n";
	out += "static GDExtensionInstanceBindingCallbacks gdsl_binding_callbacks = {\n";
	out += "	gdsl_binding_create, /* create_callback */\n";
	out += "	NULL, /* free_callback */\n";
	out += "	NULL /* reference_callback */\n";
	out += "};\n";
	out += "\n";

	// ---- 信号名缓存（每个唯一信号名一个 static StringName，init 时创建） ----
	for (const std::string &sig : signal_names) {
		out += "static gdsl_StringName gdsl_signal_" + sig + ";\n";
	}
	if (!signal_names.empty()) {
		out += "\n";
	}

	// ---- emit_signal helper ----
	out += "/* Emit a zero-arg signal named by a cached (static) StringName. */\n";
	out += "static void gdsl_emit_signal(GDExtensionObjectPtr p_object, gdsl_StringName *p_signal_name) {\n";
	out += "	if (gdsl_emit_signal_mb == NULL) {\n";
	out += "		return;\n";
	out += "	}\n";
	out += "	gdsl_Variant v_signal;\n";
	out += "	GDExtensionVariantFromTypeConstructorFunc ctor = gdsl_get_variant_from_type_constructor(GDEXTENSION_VARIANT_TYPE_STRING_NAME);\n";
	out += "	ctor((GDExtensionUninitializedVariantPtr)&v_signal, (GDExtensionTypePtr)p_signal_name);\n";
	out += "\n";
	out += "	gdsl_Variant v_ret;\n";
	out += "	GDExtensionConstVariantPtr args[1];\n";
	out += "	args[0] = (GDExtensionConstVariantPtr)&v_signal;\n";
	out += "	GDExtensionCallError err = { 0 };\n";
	out += "	gdsl_object_method_bind_call(gdsl_emit_signal_mb, p_object, args, 1, (GDExtensionUninitializedVariantPtr)&v_ret, &err);\n";
	out += "\n";
	out += "	gdsl_variant_destroy((GDExtensionVariantPtr)&v_signal);\n";
	out += "	gdsl_variant_destroy((GDExtensionVariantPtr)&v_ret);\n";
	out += "}\n";
	out += "\n";

	// ---- 每类型的 struct + 生命周期 ----
	for (const TypedType &t : prog.types) {
		const std::string pfx = fn_prefix(t.name);
		out += "/* ---- type " + t.name + " @extends " + t.base + " ---- */\n";
		out += "typedef struct {\n";
		out += "\tGDExtensionObjectPtr object;\n";
		for (const TypedField &f : t.fields) {
			out += "\t" + c_field_type(f) + " " + f.name + ";\n";
		}
		out += "} " + t.name + ";\n";
		out += "\n";
		out += "static void " + pfx + "_constructor(" + t.name + " *self) {\n";
		for (const TypedField &f : t.fields) {
			out += "\tself->" + f.name + " = " + default_literal(f) + ";\n";
		}
		out += "}\n";
		out += "\n";
		out += "static void " + pfx + "_destructor(" + t.name + " *self) {\n";
		out += "}\n";
		out += "\n";
		out += "static GDExtensionObjectPtr " + pfx + "_create_instance(void *p_class_userdata, GDExtensionBool p_notify_postinitialize) {\n";
		out += "\tgdsl_StringName parent_name;\n";
		out += "\tgdsl_string_name_new(&parent_name, \"" + t.base + "\", false);\n";
		out += "\tGDExtensionObjectPtr object = gdsl_classdb_construct_object(&parent_name);\n";
		out += "\n";
		out += "\t" + t.name + " *self = (" + t.name + " *)gdsl_mem_alloc(sizeof(" + t.name + "));\n";
		out += "\t" + pfx + "_constructor(self);\n";
		out += "\tself->object = object;\n";
		out += "\n";
		out += "\tgdsl_StringName class_name;\n";
		out += "	gdsl_string_name_new(&class_name, \"" + t.name + "\", false);\n";
		out += "	gdsl_object_set_instance(object, &class_name, (GDExtensionClassInstancePtr)self);\n";
		out += "	gdsl_object_set_instance_binding(object, gdsl_library, self, &gdsl_binding_callbacks);\n";
		out += "	return object;\n";
		out += "}\n";
		out += "\n";
		out += "static void " + pfx + "_free_instance(void *p_class_userdata, GDExtensionClassInstancePtr p_instance) {\n";
		out += "	if (p_instance == NULL) {\n";
		out += "		return;\n";
		out += "	}\n";
		out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
		out += "	" + pfx + "_destructor(self);\n";
		out += "	gdsl_mem_free(self);\n";
		out += "}\n";
		out += "\n";
		// Hot-reload support (required for the extension to be marked reloadable, which
		// enables instance tracking so the engine can clear dangling _extension pointers
		// on leaked instances at shutdown — godotengine/godot#98182).
		out += "static GDExtensionClassInstancePtr " + pfx + "_recreate_instance(void *p_class_userdata, GDExtensionObjectPtr p_object) {\n";
		out += "	" + t.name + " *self = (" + t.name + " *)gdsl_mem_alloc(sizeof(" + t.name + "));\n";
		out += "	" + pfx + "_constructor(self);\n";
		out += "	self->object = p_object;\n";
		out += "	gdsl_object_set_instance_binding(p_object, gdsl_library, self, &gdsl_binding_callbacks);\n";
		out += "	return (GDExtensionClassInstancePtr)self;\n";
		out += "}\n";
		out += "\n";
		// getter/setter methods for state fields (hot-reload state preservation via
		// Godot's property system — prepare_reload saves via get, finish_reload restores
		// via set). Only scalar types for now; Named/String are handled separately.
		for (const TypedField &f : t.fields) {
			// Named field (object reference): marshal as OBJECT, resolve via instance binding.
			if (f.type == ValueType::Named) {
				const std::string getter = pfx + "_get_" + f.name;
				const std::string setter = pfx + "_set_" + f.name;
				const std::string ty = f.type_name;
				out += "static void " + getter + "_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {\n";
				out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
				out += "	if (self->" + f.name + " == NULL) {\n";
				out += "		gdsl_variant_new_nil((GDExtensionUninitializedVariantPtr)r_return);\n";
				out += "		return;\n";
				out += "	}\n";
				out += "	GDExtensionObjectPtr obj = self->" + f.name + "->object;\n";
				out += "	GDExtensionVariantFromTypeConstructorFunc ctor = gdsl_get_variant_from_type_constructor(GDEXTENSION_VARIANT_TYPE_OBJECT);\n";
				out += "	ctor((GDExtensionUninitializedVariantPtr)r_return, (GDExtensionTypePtr)&obj);\n";
				out += "}\n";
				out += "static void " + getter + "_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {\n";
				out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
				out += "	*(GDExtensionObjectPtr *)r_ret = (self->" + f.name + " != NULL) ? self->" + f.name + "->object : NULL;\n";
				out += "}\n";
				out += "static void " + setter + "_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {\n";
				out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
				out += "	if (gdsl_variant_get_type((GDExtensionConstVariantPtr)p_args[0]) == GDEXTENSION_VARIANT_TYPE_NIL) {\n";
				out += "		self->" + f.name + " = NULL;\n";
				out += "		return;\n";
				out += "	}\n";
				out += "	GDExtensionObjectPtr obj = NULL;\n";
				out += "	GDExtensionTypeFromVariantConstructorFunc to_type = gdsl_get_variant_to_type_constructor(GDEXTENSION_VARIANT_TYPE_OBJECT);\n";
				out += "	to_type((GDExtensionUninitializedTypePtr)&obj, (GDExtensionVariantPtr)p_args[0]);\n";
				out += "	self->" + f.name + " = (" + ty + " *)gdsl_object_get_instance_binding(obj, gdsl_library, &gdsl_binding_callbacks);\n";
				out += "}\n";
				out += "static void " + setter + "_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {\n";
				out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
				out += "	GDExtensionObjectPtr obj = *(GDExtensionObjectPtr *)p_args[0];\n";
				out += "	self->" + f.name + " = (obj != NULL) ? (" + ty + " *)gdsl_object_get_instance_binding(obj, gdsl_library, &gdsl_binding_callbacks) : NULL;\n";
				out += "}\n";
				out += "\n";
				continue;
			}
			const char *vt = variant_type(f.type);
			if (!vt) {
				continue;
			}
			const std::string getter = pfx + "_get_" + f.name;
			const std::string setter = pfx + "_set_" + f.name;
			const std::string cty = c_scalar_type(f.type);
			out += "static void " + getter + "_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {\n";
			out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
			out += "	GDExtensionVariantFromTypeConstructorFunc ctor = gdsl_get_variant_from_type_constructor(" + std::string(vt) + ");\n";
			out += "	ctor((GDExtensionUninitializedVariantPtr)r_return, (GDExtensionTypePtr)&self->" + f.name + ");\n";
			out += "}\n";
			out += "static void " + getter + "_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {\n";
			out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
			out += "	*(" + cty + " *)r_ret = self->" + f.name + ";\n";
			out += "}\n";
			out += "static void " + setter + "_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {\n";
			out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
			out += "	GDExtensionTypeFromVariantConstructorFunc to_type = gdsl_get_variant_to_type_constructor(" + std::string(vt) + ");\n";
			out += "	to_type((GDExtensionUninitializedTypePtr)&self->" + f.name + ", (GDExtensionVariantPtr)p_args[0]);\n";
			out += "}\n";
			out += "static void " + setter + "_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {\n";
			out += "	" + t.name + " *self = (" + t.name + " *)p_instance;\n";
			out += "	self->" + f.name + " = *(" + cty + " *)p_args[0];\n";
			out += "}\n";
			out += "\n";
		}
	}

	// ---- 规则 → 方法（effect codegen：guard + set_field + emit，self/target） ----
	for (const TypedRule &r : prog.rules) {
		const std::string pfx = fn_prefix(r.by);
		const std::string mname = to_snake_case(r.name);
		const bool has_target = !r.target.empty();
		out += "/* ---- rule " + r.name + " by " + r.by + (has_target ? " target " + r.target : "") + " ---- */\n";
		// _impl：规则主体。有 target 时多收一个 Object 指针，经 instance binding 取 target 的 C struct。
		out += "static void " + pfx + "_" + mname + "_impl(" + r.by + " *self";
		if (has_target) {
			out += ", GDExtensionObjectPtr p_target";
		}
		out += ") {\n";
		if (has_target) {
			out += "	" + r.target + " *target = (" + r.target + " *)gdsl_object_get_instance_binding(p_target, gdsl_library, &gdsl_binding_callbacks);\n";
			out += "	if (target == NULL) {\n";
			out += "		return;\n";
			out += "	}\n";
		}
		{
			const std::string gself = (r.guard.ref == RefOwner::Target) ? "target" : "self";
			out += "	if (!(" + gself + "->" + r.guard.field + " " + r.guard.cmp + " " + r.guard.value + ")) {\n";
		}
		out += "		return;\n";
		out += "	}\n";
		for (const Effect &fx : r.effects) {
			if (fx.kind == EffectKind::Emit) {
				out += "	gdsl_emit_signal(self->object, &gdsl_signal_" + fx.signal_name + ");\n";
			} else {
				const std::string fxself = (fx.ref == RefOwner::Target) ? "target" : "self";
				if (fx.kind == EffectKind::Set) {
					out += "	" + fxself + "->" + fx.field + " = " + fx.value + ";\n";
				} else if (fx.kind == EffectKind::Add) {
					out += "	" + fxself + "->" + fx.field + " += " + fx.value + ";\n";
				} else { // Sub
					out += "	" + fxself + "->" + fx.field + " -= " + fx.value + ";\n";
				}
			}
		}
		out += "}\n";
		out += "\n";
		// _call（Variant 路径）：有 target 时从 Variant 里解出 Object 指针。
		out += "static void " + pfx + "_" + mname + "_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {\n";
		if (has_target) {
			out += "	GDExtensionObjectPtr p_target = NULL;\n";
			out += "	if (p_argument_count >= 1 && p_args != NULL) {\n";
			out += "		GDExtensionTypeFromVariantConstructorFunc to_type = gdsl_get_variant_to_type_constructor(GDEXTENSION_VARIANT_TYPE_OBJECT);\n";
			out += "		to_type((GDExtensionUninitializedTypePtr)&p_target, (GDExtensionVariantPtr)p_args[0]);\n";
			out += "	}\n";
			out += "	" + pfx + "_" + mname + "_impl((" + r.by + " *)p_instance, p_target);\n";
		} else {
			out += "	" + pfx + "_" + mname + "_impl((" + r.by + " *)p_instance);\n";
		}
		out += "}\n";
		out += "\n";
		// _ptr（ptrcall 路径）：p_args[0] 指向 GDExtensionObjectPtr。
		out += "static void " + pfx + "_" + mname + "_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {\n";
		if (has_target) {
			out += "	GDExtensionObjectPtr p_target = (p_args != NULL) ? *(GDExtensionObjectPtr *)p_args[0] : NULL;\n";
			out += "	" + pfx + "_" + mname + "_impl((" + r.by + " *)p_instance, p_target);\n";
		} else {
			out += "	" + pfx + "_" + mname + "_impl((" + r.by + " *)p_instance);\n";
		}
		out += "}\n";
		out += "\n";
	}

	// ---- 初始化 / 反初始化 / 入口点 ----
	out += "static void gdsl_initialize(void *p_userdata, GDExtensionInitializationLevel p_level) {\n";
	out += "\tif (p_level != GDEXTENSION_INITIALIZATION_SCENE) {\n";
	out += "\t\treturn;\n";
	out += "\t}\n";
	// 缓存 Object::emit_signal MethodBind（信号发射经 method-bind call 路径）。
	out += "\t{\n";
	out += "\t\tgdsl_StringName sn_Object;\n";
	out += "\t\tgdsl_StringName sn_emit_signal;\n";
	out += "\t\tgdsl_string_name_new(&sn_Object, \"Object\", true);\n";
	out += "\t\tgdsl_string_name_new(&sn_emit_signal, \"emit_signal\", true);\n";
	out += "\t\tgdsl_emit_signal_mb = gdsl_classdb_get_method_bind(&sn_Object, &sn_emit_signal, " + emit_hash + ");\n";
	out += "\t}\n";
	// 缓存每个唯一信号名的 static StringName。
	for (const std::string &sig : signal_names) {
		out += "	gdsl_string_name_new(&gdsl_signal_" + sig + ", \"" + sig + "\", true);\n";
	}
	for (const TypedType &t : prog.types) {
		const std::string pfx = fn_prefix(t.name);
		out += "\t{\n";
		out += "\t\tgdsl_StringName class_name;\n";
		out += "\t\tgdsl_StringName parent_name;\n";
		out += "\t\tgdsl_string_name_new(&class_name, \"" + t.name + "\", false);\n";
		out += "\t\tgdsl_string_name_new(&parent_name, \"" + t.base + "\", false);\n";
		out += "\t\tGDExtensionClassCreationInfo6 class_info = { 0 };\n";
		out += "\t\tclass_info.is_exposed = 1;\n";
		out += "		class_info.create_instance_func = " + pfx + "_create_instance;\n";
		out += "		class_info.free_instance_func = " + pfx + "_free_instance;\n";
		out += "		class_info.recreate_instance_func = " + pfx + "_recreate_instance;\n";
		out += "\t\tgdsl_classdb_register_extension_class6(gdsl_library, &class_name, &parent_name, &class_info);\n";
		for (const TypedRule &r : prog.rules) {
			if (r.by != t.name) {
				continue;
			}
			const std::string mname = to_snake_case(r.name);
			out += "\t\t{\n";
			out += "\t\t\tgdsl_StringName method_name;\n";
			out += "\t\t\tgdsl_string_name_new(&method_name, \"" + mname + "\", false);\n";
			out += "\t\t\tGDExtensionClassMethodInfo method_info = { 0 };\n";
			out += "\t\t\tmethod_info.name = (GDExtensionStringNamePtr)&method_name;\n";
			out += "\t\t\tmethod_info.call_func = " + pfx + "_" + mname + "_call;\n";
			out += "\t\t\tmethod_info.ptrcall_func = " + pfx + "_" + mname + "_ptr;\n";
			out += "\t\t\tmethod_info.method_flags = GDEXTENSION_METHOD_FLAG_NORMAL;\n";
			out += "			method_info.has_return_value = 0;\n";
			if (!r.target.empty()) {
				out += "			GDExtensionPropertyInfo arg_info[1];\n";
				out += "			gdsl_StringName arg_name;\n";
				out += "			gdsl_string_name_new(&arg_name, \"target\", false);\n";
				out += "			arg_info[0].type = GDEXTENSION_VARIANT_TYPE_OBJECT;\n";
				out += "			arg_info[0].name = (GDExtensionStringNamePtr)&arg_name;\n";
				out += "			gdsl_StringName target_class_name;\n";
				out += "			gdsl_string_name_new(&target_class_name, \"" + r.target + "\", false);\n";
				out += "			arg_info[0].class_name = (GDExtensionStringNamePtr)&target_class_name;\n";
				out += "			arg_info[0].hint = 0;\n";
				out += "			arg_info[0].hint_string = (GDExtensionStringPtr)gdsl_empty_string;\n";
				out += "			arg_info[0].usage = 0;\n";
				out += "			GDExtensionClassMethodArgumentMetadata arg_meta[1];\n";
				out += "			arg_meta[0] = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;\n";
				out += "			method_info.argument_count = 1;\n";
				out += "			method_info.arguments_info = arg_info;\n";
				out += "			method_info.arguments_metadata = arg_meta;\n";
			} else {
				out += "			method_info.argument_count = 0;\n";
			}
			out += "			gdsl_classdb_register_extension_class_method(gdsl_library, &class_name, &method_info);\n";
			out += "		}\n";
		}
		// getter/setter + property registration for state fields (hot-reload state
		// preservation: prepare_reload saves via get, finish_reload restores via set).
		for (const TypedField &f : t.fields) {
			std::string vtype;
			std::string clsname;
			if (f.type == ValueType::Named) {
				vtype = "GDEXTENSION_VARIANT_TYPE_OBJECT";
				clsname = f.type_name;
			} else {
				const char *vt = variant_type(f.type);
				if (!vt) {
					continue;
				}
				vtype = vt;
				clsname = "";
			}
			const std::string getter = pfx + "_get_" + f.name;
			const std::string setter = pfx + "_set_" + f.name;
			// getter method
			out += "		{\n";
			out += "			gdsl_StringName mn;\n";
			out += "			gdsl_string_name_new(&mn, \"get_" + f.name + "\", false);\n";
			out += "			GDExtensionClassMethodInfo mi = { 0 };\n";
			out += "			mi.name = (GDExtensionStringNamePtr)&mn;\n";
			out += "			mi.call_func = " + getter + "_call;\n";
			out += "			mi.ptrcall_func = " + getter + "_ptr;\n";
			out += "			mi.method_flags = GDEXTENSION_METHOD_FLAG_NORMAL;\n";
			out += "			mi.has_return_value = 1;\n";
			out += "			GDExtensionPropertyInfo ri;\n";
			out += "			gdsl_StringName rn;\n";
			out += "			gdsl_string_name_new(&rn, \"\", false);\n";
			out += "			gdsl_StringName rc;\n";
			out += "			gdsl_string_name_new(&rc, \"" + clsname + "\", false);\n";
			out += "			ri.type = " + vtype + ";\n";
			out += "			ri.name = (GDExtensionStringNamePtr)&rn;\n";
			out += "			ri.class_name = (GDExtensionStringNamePtr)&rc;\n";
			out += "			ri.hint = 0;\n";
			out += "			ri.hint_string = (GDExtensionStringPtr)gdsl_empty_string;\n";
			out += "			ri.usage = 0;\n";
			out += "			mi.return_value_info = &ri;\n";
			out += "			gdsl_classdb_register_extension_class_method(gdsl_library, &class_name, &mi);\n";
			out += "		}\n";
			// setter method
			out += "		{\n";
			out += "			gdsl_StringName mn;\n";
			out += "			gdsl_string_name_new(&mn, \"set_" + f.name + "\", false);\n";
			out += "			GDExtensionClassMethodInfo mi = { 0 };\n";
			out += "			mi.name = (GDExtensionStringNamePtr)&mn;\n";
			out += "			mi.call_func = " + setter + "_call;\n";
			out += "			mi.ptrcall_func = " + setter + "_ptr;\n";
			out += "			mi.method_flags = GDEXTENSION_METHOD_FLAG_NORMAL;\n";
			out += "			mi.has_return_value = 0;\n";
			out += "			GDExtensionPropertyInfo ai;\n";
			out += "			gdsl_StringName an;\n";
			out += "			gdsl_string_name_new(&an, \"value\", false);\n";
			out += "			gdsl_StringName ac;\n";
			out += "			gdsl_string_name_new(&ac, \"" + clsname + "\", false);\n";
			out += "			ai.type = " + vtype + ";\n";
			out += "			ai.name = (GDExtensionStringNamePtr)&an;\n";
			out += "			ai.class_name = (GDExtensionStringNamePtr)&ac;\n";
			out += "			ai.hint = 0;\n";
			out += "			ai.hint_string = (GDExtensionStringPtr)gdsl_empty_string;\n";
			out += "			ai.usage = 0;\n";
			out += "			GDExtensionClassMethodArgumentMetadata am = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;\n";
			out += "			mi.argument_count = 1;\n";
			out += "			mi.arguments_info = &ai;\n";
			out += "			mi.arguments_metadata = &am;\n";
			out += "			gdsl_classdb_register_extension_class_method(gdsl_library, &class_name, &mi);\n";
			out += "		}\n";
			// property
			out += "		{\n";
			out += "			gdsl_StringName pn;\n";
			out += "			gdsl_string_name_new(&pn, \"" + f.name + "\", false);\n";
			out += "			gdsl_StringName sn;\n";
			out += "			gdsl_string_name_new(&sn, \"set_" + f.name + "\", false);\n";
			out += "			gdsl_StringName gn;\n";
			out += "			gdsl_string_name_new(&gn, \"get_" + f.name + "\", false);\n";
			out += "			GDExtensionPropertyInfo pi;\n";
			out += "			gdsl_StringName pc;\n";
			out += "			gdsl_string_name_new(&pc, \"" + clsname + "\", false);\n";
			out += "			pi.type = " + vtype + ";\n";
			out += "			pi.name = (GDExtensionStringNamePtr)&pn;\n";
			out += "			pi.class_name = (GDExtensionStringNamePtr)&pc;\n";
			out += "			pi.hint = 0;\n";
			out += "			pi.hint_string = (GDExtensionStringPtr)gdsl_empty_string;\n";
			out += "			pi.usage = 2; /* PROPERTY_USAGE_STORAGE */\n";
			out += "			gdsl_classdb_register_extension_class_property(gdsl_library, &class_name, &pi, &sn, &gn);\n";
			out += "		}\n";
		}
		out += "	}\n";
	}
	out += "}\n";
	out += "\n";
	out += "static void gdsl_deinitialize(void *p_userdata, GDExtensionInitializationLevel p_level) {\n";
	out += "	if (p_level != GDEXTENSION_INITIALIZATION_SCENE) {\n";
	out += "		return;\n";
	out += "	}\n";
	// Unregister classes in reverse order (inheritors before parents) so hot-reload
	// can convert live instances to placeholders and back.
	for (size_t i = prog.types.size(); i-- > 0;) {
		const TypedType &t = prog.types[i];
		out += "	{\n";
		out += "		gdsl_StringName unreg_name;\n";
		out += "		gdsl_string_name_new(&unreg_name, \"" + t.name + "\", false);\n";
		out += "		gdsl_classdb_unregister_extension_class(gdsl_library, &unreg_name);\n";
		out += "	}\n";
	}
	out += "}\n";
	out += "\n";
	out += "GDExtensionBool GDE_EXPORT gdsl_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {\n";
	out += "\tgdsl_library = p_library;\n";
	out += "\tgdsl_load_api(p_get_proc_address);\n";
	out += "\tr_initialization->initialize = gdsl_initialize;\n";
	out += "\tr_initialization->deinitialize = gdsl_deinitialize;\n";
	out += "\tr_initialization->userdata = NULL;\n";
	out += "\tr_initialization->minimum_initialization_level = GDEXTENSION_INITIALIZATION_SCENE;\n";
	out += "\treturn 1;\n";
	out += "}\n";
	out += "\n";

	return out;
}

} // namespace gdsl
