#include "doctest.h"
#include "parser.h"
#include "typecheck.h"
#include "codegen_logic.h"

static gdsl::TypedProgram typed_program(const char *src) {
	gdsl::Program p;
	std::string err;
	REQUIRE(gdsl::parse_program(src, p, err));
	gdsl::TypedProgram typed;
	REQUIRE(gdsl::typecheck(p, typed, err));
	return typed;
}

TEST_CASE("[GDSL] Emit C golden output") {
	const gdsl::TypedProgram typed = typed_program(
			"type Player @extends CharacterBody2D\n"
			"state:\n"
			"    hp: int = 3\n"
			"    speed: float = 400.0\n");

	const std::string expected =
			"/* Generated by gdsl. Do not edit. */\n"
			"#include <stdint.h>\n"
			"\n"
			"typedef struct Player {\n"
			"\tint64_t hp; /* 3 */\n"
			"\tdouble speed; /* 400.0 */\n"
			"} Player;\n"
			"\n";
	CHECK(gdsl::emit_c(typed) == expected);
}

TEST_CASE("[GDSL] Emit C maps named field to pointer") {
	const gdsl::TypedProgram typed = typed_program(
			"type Weapon @extends Resource\n"
			"\n"
			"type Player @extends Node2D\n"
			"state:\n"
			"    weapon: Weapon = null\n");

	const std::string c = gdsl::emit_c(typed);
	CHECK(c.find("typedef struct Weapon {") != std::string::npos);
	CHECK(c.find("Weapon * weapon;") != std::string::npos);
}

TEST_CASE("[GDSL] Emit C includes rule comments") {
	const gdsl::TypedProgram typed = typed_program(
			"type Bullet @extends Area2D\n"
			"\n"
			"rule OnHit by Bullet:\n"
			"    when target.hp > 0\n"
			"    then target.hp -= 1, emit(hit)\n");

	const std::string c = gdsl::emit_c(typed);
	CHECK(c.find("/* rule OnHit by Bullet: when `target.hp > 0` then `target.hp -= 1, emit(hit)` */") != std::string::npos);
}

TEST_CASE("[GDSL] Emit C is deterministic") {
	const gdsl::TypedProgram typed = typed_program(
			"type Player @extends Node2D\n"
			"state:\n"
			"    hp: int = 3\n");

	const std::string a = gdsl::emit_c(typed);
	const std::string b = gdsl::emit_c(typed);
	CHECK_FALSE(a.empty());
	CHECK(a == b);
}
