/* Generated by gdsl. Do not edit. */
#include <gdextension_interface.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if !defined(GDE_EXPORT)
#if defined(_WIN32)
#define GDE_EXPORT __declspec(dllexport)
#elif defined(__GNUC__)
#define GDE_EXPORT __attribute__((visibility("default")))
#else
#define GDE_EXPORT
#endif
#endif

/* ---- GDExtension API cache ---- */
static GDExtensionClassLibraryPtr gdsl_library = NULL;

static GDExtensionInterfaceStringNameNewWithLatin1Chars gdsl_string_name_new;
static GDExtensionInterfaceClassdbConstructObject gdsl_classdb_construct_object;
static GDExtensionInterfaceObjectSetInstance gdsl_object_set_instance;
static GDExtensionInterfaceMemAlloc gdsl_mem_alloc;
static GDExtensionInterfaceMemFree gdsl_mem_free;
static GDExtensionInterfaceClassdbRegisterExtensionClass6 gdsl_classdb_register_extension_class6;
static GDExtensionInterfaceClassdbRegisterExtensionClassMethod gdsl_classdb_register_extension_class_method;
static GDExtensionInterfaceClassdbGetMethodBind gdsl_classdb_get_method_bind;
static GDExtensionInterfaceObjectMethodBindCall gdsl_object_method_bind_call;
static GDExtensionInterfaceGetVariantFromTypeConstructor gdsl_get_variant_from_type_constructor;
static GDExtensionInterfaceVariantDestroy gdsl_variant_destroy;
static GDExtensionInterfaceVariantNewNil gdsl_variant_new_nil;
static GDExtensionInterfaceVariantGetType gdsl_variant_get_type;
static GDExtensionInterfaceObjectSetInstanceBinding gdsl_object_set_instance_binding;
static GDExtensionInterfaceObjectGetInstanceBinding gdsl_object_get_instance_binding;
static GDExtensionInterfaceGetVariantToTypeConstructor gdsl_get_variant_to_type_constructor;
static GDExtensionInterfaceClassdbUnregisterExtensionClass gdsl_classdb_unregister_extension_class;
static GDExtensionInterfaceClassdbRegisterExtensionClassProperty gdsl_classdb_register_extension_class_property;

static void gdsl_load_api(GDExtensionInterfaceGetProcAddress p_get_proc_address) {
	gdsl_string_name_new = (GDExtensionInterfaceStringNameNewWithLatin1Chars)p_get_proc_address("string_name_new_with_latin1_chars");
	gdsl_classdb_construct_object = (GDExtensionInterfaceClassdbConstructObject)p_get_proc_address("classdb_construct_object");
	gdsl_object_set_instance = (GDExtensionInterfaceObjectSetInstance)p_get_proc_address("object_set_instance");
	gdsl_mem_alloc = (GDExtensionInterfaceMemAlloc)p_get_proc_address("mem_alloc");
	gdsl_mem_free = (GDExtensionInterfaceMemFree)p_get_proc_address("mem_free");
	gdsl_classdb_register_extension_class6 = (GDExtensionInterfaceClassdbRegisterExtensionClass6)p_get_proc_address("classdb_register_extension_class6");
	gdsl_classdb_register_extension_class_method = (GDExtensionInterfaceClassdbRegisterExtensionClassMethod)p_get_proc_address("classdb_register_extension_class_method");
	gdsl_classdb_get_method_bind = (GDExtensionInterfaceClassdbGetMethodBind)p_get_proc_address("classdb_get_method_bind");
	gdsl_object_method_bind_call = (GDExtensionInterfaceObjectMethodBindCall)p_get_proc_address("object_method_bind_call");
	gdsl_get_variant_from_type_constructor = (GDExtensionInterfaceGetVariantFromTypeConstructor)p_get_proc_address("get_variant_from_type_constructor");
	gdsl_variant_destroy = (GDExtensionInterfaceVariantDestroy)p_get_proc_address("variant_destroy");
	gdsl_variant_new_nil = (GDExtensionInterfaceVariantNewNil)p_get_proc_address("variant_new_nil");
	gdsl_variant_get_type = (GDExtensionInterfaceVariantGetType)p_get_proc_address("variant_get_type");
	gdsl_object_set_instance_binding = (GDExtensionInterfaceObjectSetInstanceBinding)p_get_proc_address("object_set_instance_binding");
	gdsl_object_get_instance_binding = (GDExtensionInterfaceObjectGetInstanceBinding)p_get_proc_address("object_get_instance_binding");
	gdsl_get_variant_to_type_constructor = (GDExtensionInterfaceGetVariantToTypeConstructor)p_get_proc_address("get_variant_to_type_constructor");
	gdsl_classdb_unregister_extension_class = (GDExtensionInterfaceClassdbUnregisterExtensionClass)p_get_proc_address("classdb_unregister_extension_class");
	gdsl_classdb_register_extension_class_property = (GDExtensionInterfaceClassdbRegisterExtensionClassProperty)p_get_proc_address("classdb_register_extension_class_property");
}

/* StringName opaque holder (64-bit build: 8 bytes). */
typedef struct {
	uint8_t data[8];
} gdsl_StringName;

/* Variant opaque holder (single-precision 64-bit build: 24 bytes, 8-aligned). */
typedef union {
	uint64_t align_;
	uint8_t data[24];
} gdsl_Variant;

/* 空 String（8 字节零初始化 = 空字符串）。PropertyInfo 构造会解引用 hint_string，
 * 不能传 NULL，故提供这个零初始化占位。 */
static uint8_t gdsl_empty_string[8] = { 0 };

/* Object::emit_signal MethodBind，SCENE 初始化时缓存一次。 */
static GDExtensionMethodBindPtr gdsl_emit_signal_mb = NULL;

/* Instance binding callbacks：把每个 DSL 对象的 C struct 挂到对象上，供跨参与者 target 取回。
 * free_callback 置 NULL —— 内存由扩展的 free_instance_func 统一释放，避免双重释放。 */
static void *gdsl_binding_create(void *p_token, GDExtensionObjectPtr p_instance) {
	(void)p_token;
	(void)p_instance;
	return NULL;
}
static GDExtensionInstanceBindingCallbacks gdsl_binding_callbacks = {
	gdsl_binding_create, /* create_callback */
	NULL, /* free_callback */
	NULL /* reference_callback */
};

/* Emit a zero-arg signal named by a cached (static) StringName. */
static void gdsl_emit_signal(GDExtensionObjectPtr p_object, gdsl_StringName *p_signal_name) {
	if (gdsl_emit_signal_mb == NULL) {
		return;
	}
	gdsl_Variant v_signal;
	GDExtensionVariantFromTypeConstructorFunc ctor = gdsl_get_variant_from_type_constructor(GDEXTENSION_VARIANT_TYPE_STRING_NAME);
	ctor((GDExtensionUninitializedVariantPtr)&v_signal, (GDExtensionTypePtr)p_signal_name);

	gdsl_Variant v_ret;
	GDExtensionConstVariantPtr args[1];
	args[0] = (GDExtensionConstVariantPtr)&v_signal;
	GDExtensionCallError err = { 0 };
	gdsl_object_method_bind_call(gdsl_emit_signal_mb, p_object, args, 1, (GDExtensionUninitializedVariantPtr)&v_ret, &err);

	gdsl_variant_destroy((GDExtensionVariantPtr)&v_signal);
	gdsl_variant_destroy((GDExtensionVariantPtr)&v_ret);
}

/* ---- type Player @extends Node2D ---- */
typedef struct {
	GDExtensionObjectPtr object;
	int64_t hp;
} Player;

static void player_constructor(Player *self) {
	self->hp = 3;
}

static void player_destructor(Player *self) {
}

static GDExtensionObjectPtr player_create_instance(void *p_class_userdata, GDExtensionBool p_notify_postinitialize) {
	gdsl_StringName parent_name;
	gdsl_string_name_new(&parent_name, "Node2D", false);
	GDExtensionObjectPtr object = gdsl_classdb_construct_object(&parent_name);

	Player *self = (Player *)gdsl_mem_alloc(sizeof(Player));
	player_constructor(self);
	self->object = object;

	gdsl_StringName class_name;
	gdsl_string_name_new(&class_name, "Player", false);
	gdsl_object_set_instance(object, &class_name, (GDExtensionClassInstancePtr)self);
	gdsl_object_set_instance_binding(object, gdsl_library, self, &gdsl_binding_callbacks);
	return object;
}

static void player_free_instance(void *p_class_userdata, GDExtensionClassInstancePtr p_instance) {
	if (p_instance == NULL) {
		return;
	}
	Player *self = (Player *)p_instance;
	player_destructor(self);
	gdsl_mem_free(self);
}

static GDExtensionClassInstancePtr player_recreate_instance(void *p_class_userdata, GDExtensionObjectPtr p_object) {
	Player *self = (Player *)gdsl_mem_alloc(sizeof(Player));
	player_constructor(self);
	self->object = p_object;
	gdsl_object_set_instance_binding(p_object, gdsl_library, self, &gdsl_binding_callbacks);
	return (GDExtensionClassInstancePtr)self;
}

static void player_get_hp_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
	Player *self = (Player *)p_instance;
	GDExtensionVariantFromTypeConstructorFunc ctor = gdsl_get_variant_from_type_constructor(GDEXTENSION_VARIANT_TYPE_INT);
	ctor((GDExtensionUninitializedVariantPtr)r_return, (GDExtensionTypePtr)&self->hp);
}
static void player_get_hp_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {
	Player *self = (Player *)p_instance;
	*(int64_t *)r_ret = self->hp;
}
static void player_set_hp_call(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstVariantPtr *p_args, GDExtensionInt p_argument_count, GDExtensionVariantPtr r_return, GDExtensionCallError *r_error) {
	Player *self = (Player *)p_instance;
	if (gdsl_variant_get_type((GDExtensionConstVariantPtr)p_args[0]) != GDEXTENSION_VARIANT_TYPE_INT) {
		return;
	}
	GDExtensionTypeFromVariantConstructorFunc to_type = gdsl_get_variant_to_type_constructor(GDEXTENSION_VARIANT_TYPE_INT);
	to_type((GDExtensionUninitializedTypePtr)&self->hp, (GDExtensionVariantPtr)p_args[0]);
}
static void player_set_hp_ptr(void *p_method_userdata, GDExtensionClassInstancePtr p_instance, const GDExtensionConstTypePtr *p_args, GDExtensionTypePtr r_ret) {
	Player *self = (Player *)p_instance;
	self->hp = *(int64_t *)p_args[0];
}

static void gdsl_initialize(void *p_userdata, GDExtensionInitializationLevel p_level) {
	if (p_level != GDEXTENSION_INITIALIZATION_SCENE) {
		return;
	}
	{
		gdsl_StringName sn_Object;
		gdsl_StringName sn_emit_signal;
		gdsl_string_name_new(&sn_Object, "Object", true);
		gdsl_string_name_new(&sn_emit_signal, "emit_signal", true);
		gdsl_emit_signal_mb = gdsl_classdb_get_method_bind(&sn_Object, &sn_emit_signal, 4047867050);
	}
	{
		gdsl_StringName class_name;
		gdsl_StringName parent_name;
		gdsl_string_name_new(&class_name, "Player", false);
		gdsl_string_name_new(&parent_name, "Node2D", false);
		GDExtensionClassCreationInfo6 class_info = { 0 };
		class_info.is_exposed = 1;
		class_info.create_instance_func = player_create_instance;
		class_info.free_instance_func = player_free_instance;
		class_info.recreate_instance_func = player_recreate_instance;
		gdsl_classdb_register_extension_class6(gdsl_library, &class_name, &parent_name, &class_info);
		{
			gdsl_StringName mn;
			gdsl_string_name_new(&mn, "get_hp", false);
			GDExtensionClassMethodInfo mi = { 0 };
			mi.name = (GDExtensionStringNamePtr)&mn;
			mi.call_func = player_get_hp_call;
			mi.ptrcall_func = player_get_hp_ptr;
			mi.method_flags = GDEXTENSION_METHOD_FLAG_NORMAL;
			mi.has_return_value = 1;
			GDExtensionPropertyInfo ri;
			gdsl_StringName rn;
			gdsl_string_name_new(&rn, "", false);
			gdsl_StringName rc;
			gdsl_string_name_new(&rc, "", false);
			ri.type = GDEXTENSION_VARIANT_TYPE_INT;
			ri.name = (GDExtensionStringNamePtr)&rn;
			ri.class_name = (GDExtensionStringNamePtr)&rc;
			ri.hint = 0;
			ri.hint_string = (GDExtensionStringPtr)gdsl_empty_string;
			ri.usage = 0;
			mi.return_value_info = &ri;
			gdsl_classdb_register_extension_class_method(gdsl_library, &class_name, &mi);
		}
		{
			gdsl_StringName mn;
			gdsl_string_name_new(&mn, "set_hp", false);
			GDExtensionClassMethodInfo mi = { 0 };
			mi.name = (GDExtensionStringNamePtr)&mn;
			mi.call_func = player_set_hp_call;
			mi.ptrcall_func = player_set_hp_ptr;
			mi.method_flags = GDEXTENSION_METHOD_FLAG_NORMAL;
			mi.has_return_value = 0;
			GDExtensionPropertyInfo ai;
			gdsl_StringName an;
			gdsl_string_name_new(&an, "value", false);
			gdsl_StringName ac;
			gdsl_string_name_new(&ac, "", false);
			ai.type = GDEXTENSION_VARIANT_TYPE_INT;
			ai.name = (GDExtensionStringNamePtr)&an;
			ai.class_name = (GDExtensionStringNamePtr)&ac;
			ai.hint = 0;
			ai.hint_string = (GDExtensionStringPtr)gdsl_empty_string;
			ai.usage = 0;
			GDExtensionClassMethodArgumentMetadata am = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
			mi.argument_count = 1;
			mi.arguments_info = &ai;
			mi.arguments_metadata = &am;
			gdsl_classdb_register_extension_class_method(gdsl_library, &class_name, &mi);
		}
		{
			gdsl_StringName pn;
			gdsl_string_name_new(&pn, "hp", false);
			gdsl_StringName sn;
			gdsl_string_name_new(&sn, "set_hp", false);
			gdsl_StringName gn;
			gdsl_string_name_new(&gn, "get_hp", false);
			GDExtensionPropertyInfo pi;
			gdsl_StringName pc;
			gdsl_string_name_new(&pc, "", false);
			pi.type = GDEXTENSION_VARIANT_TYPE_INT;
			pi.name = (GDExtensionStringNamePtr)&pn;
			pi.class_name = (GDExtensionStringNamePtr)&pc;
			pi.hint = 0;
			pi.hint_string = (GDExtensionStringPtr)gdsl_empty_string;
			pi.usage = 2; /* PROPERTY_USAGE_STORAGE */
			gdsl_classdb_register_extension_class_property(gdsl_library, &class_name, &pi, &sn, &gn);
		}
	}
}

static void gdsl_deinitialize(void *p_userdata, GDExtensionInitializationLevel p_level) {
	if (p_level != GDEXTENSION_INITIALIZATION_SCENE) {
		return;
	}
	{
		gdsl_StringName unreg_name;
		gdsl_string_name_new(&unreg_name, "Player", false);
		gdsl_classdb_unregister_extension_class(gdsl_library, &unreg_name);
	}
}

GDExtensionBool GDE_EXPORT gdsl_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	gdsl_library = p_library;
	gdsl_load_api(p_get_proc_address);
	r_initialization->initialize = gdsl_initialize;
	r_initialization->deinitialize = gdsl_deinitialize;
	r_initialization->userdata = NULL;
	r_initialization->minimum_initialization_level = GDEXTENSION_INITIALIZATION_SCENE;
	return 1;
}

